version: "3.1"


volumes:
  db: {}

services:
  app:
    #    image: postgres:14
    command: rails server -b 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_USER: root
      DB_PASSWORD: root
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root