development:
  adapter: postgresql
  encoding: unicode
  database: gorn_db_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: gorn_db_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: gorn_db
  pool: 5
